import { NextPage } from "next";
import Head from "next/head";
import SideNav from "../components/SideNav";
import TransactionTable from "../components/Table/TransactionTable";
import Wrapper from "../components/Wrapper";

const Accounts: NextPage = () => {
  return (
    <>
      <Head>
        <title>Accounts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <SideNav />
      </Wrapper>
    </>
  );
};

export default Accounts;
