import { NextPage } from "next";
import Head from "next/head";
import SideNav from "../components/SideNav";
import TransactionTable from "../components/Table/TransactionTable";
import Wrapper from "../components/Wrapper";

const Transactions: NextPage = () => {
  return (
    <>
      <Head>
        <title>Transactions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <SideNav />
        <div className="max-w-8xl mx-auto mt-10 h-full w-full px-2">
          <TransactionTable />
        </div>
      </Wrapper>
    </>
  );
};

export default Transactions;
